# Generated by Django 4.2 on 2023-04-14 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="song",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Singer",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
