# Generated by Django 4.2 on 2023-05-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0004_song_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="singer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="dash.singer",
            ),
        ),
    ]
